version: 2

models:
  - name: fct_seller_performance
    columns:
      - name: seller_id
        tests:
          - unique
          - not_null
      - name: total_revenue
        tests:
          - not_null:
              config:
                severity: warn
      - name: total_orders
        tests:
          - not_null:
              config:
                severity: warn

  - name: dim_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: product_category_name
        tests:
          - not_null:
              config:
                severity: warn